// Datos preestablecidos de partidos para Fase de Grupos (72 partidos, 12 grupos)
export const GROUP_MATCHES = [
  { match_number: 1, group_name: "A", team_local: "México", team_visitor: "Sudáfrica", date: "2026-06-11" },
  { match_number: 2, group_name: "A", team_local: "Corea del Sur", team_visitor: "Rep. Checa", date: "2026-06-11" },
  { match_number: 3, group_name: "A", team_local: "México", team_visitor: "Corea del Sur", date: "2026-06-18" },
  { match_number: 4, group_name: "A", team_local: "Sudáfrica", team_visitor: "Rep. Checa", date: "2026-06-18" },
  { match_number: 5, group_name: "A", team_local: "México", team_visitor: "Rep. Checa", date: "2026-06-24" },
  { match_number: 6, group_name: "A", team_local: "Sudáfrica", team_visitor: "Corea del Sur", date: "2026-06-24" },
  { match_number: 7, group_name: "B", team_local: "Canadá", team_visitor: "Qatar", date: "2026-06-18" },
  { match_number: 8, group_name: "B", team_local: "Bosnia y Herz.", team_visitor: "Suiza", date: "2026-06-18" },
  { match_number: 9, group_name: "B", team_local: "Canadá", team_visitor: "Bosnia y Herz.", date: "2026-06-12" },
  { match_number: 10, group_name: "B", team_local: "Qatar", team_visitor: "Suiza", date: "2026-06-13" },
  { match_number: 11, group_name: "B", team_local: "Canadá", team_visitor: "Suiza", date: "2026-06-24" },
  { match_number: 12, group_name: "B", team_local: "Bosnia y Herz.", team_visitor: "Qatar", date: "2026-06-24" },
  { match_number: 13, group_name: "C", team_local: "Brasil", team_visitor: "Marruecos", date: "2026-06-13" },
  { match_number: 14, group_name: "C", team_local: "Haití", team_visitor: "Escocia", date: "2026-06-13" },
  { match_number: 15, group_name: "C", team_local: "Brasil", team_visitor: "Haití", date: "2026-06-19" },
  { match_number: 16, group_name: "C", team_local: "Marruecos", team_visitor: "Escocia", date: "2026-06-19" },
  { match_number: 17, group_name: "C", team_local: "Brasil", team_visitor: "Escocia", date: "2026-06-24" },
  { match_number: 18, group_name: "C", team_local: "Marruecos", team_visitor: "Haití", date: "2026-06-24" },
  { match_number: 19, group_name: "D", team_local: "EE.UU.", team_visitor: "Paraguay", date: "2026-06-12" },
  { match_number: 20, group_name: "D", team_local: "Australia", team_visitor: "Turquía", date: "2026-06-13" },
  { match_number: 21, group_name: "D", team_local: "EE.UU.", team_visitor: "Australia", date: "2026-06-19" },
  { match_number: 22, group_name: "D", team_local: "Paraguay", team_visitor: "Turquía", date: "2026-06-19" },
  { match_number: 23, group_name: "D", team_local: "EE.UU.", team_visitor: "Turquía", date: "2026-06-25" },
  { match_number: 24, group_name: "D", team_local: "Paraguay", team_visitor: "Australia", date: "2026-06-25" },
  { match_number: 25, group_name: "E", team_local: "Alemania", team_visitor: "Curazao", date: "2026-06-14" },
  { match_number: 26, group_name: "E", team_local: "Costa de Marfil", team_visitor: "Ecuador", date: "2026-06-14" },
  { match_number: 27, group_name: "E", team_local: "Alemania", team_visitor: "Costa de Marfil", date: "2026-06-20" },
  { match_number: 28, group_name: "E", team_local: "Curazao", team_visitor: "Ecuador", date: "2026-06-20" },
  { match_number: 29, group_name: "E", team_local: "Alemania", team_visitor: "Ecuador", date: "2026-06-25" },
  { match_number: 30, group_name: "E", team_local: "Costa de Marfil", team_visitor: "Curazao", date: "2026-06-25" },
  { match_number: 31, group_name: "F", team_local: "Países Bajos", team_visitor: "Japón", date: "2026-06-14" },
  { match_number: 32, group_name: "F", team_local: "Suecia", team_visitor: "Túnez", date: "2026-06-14" },
  { match_number: 33, group_name: "F", team_local: "Países Bajos", team_visitor: "Suecia", date: "2026-06-20" },
  { match_number: 34, group_name: "F", team_local: "Japón", team_visitor: "Túnez", date: "2026-06-20" },
  { match_number: 35, group_name: "F", team_local: "Países Bajos", team_visitor: "Túnez", date: "2026-06-25" },
  { match_number: 36, group_name: "F", team_local: "Japón", team_visitor: "Suecia", date: "2026-06-25" },
  { match_number: 37, group_name: "G", team_local: "Bélgica", team_visitor: "Egipto", date: "2026-06-15" },
  { match_number: 38, group_name: "G", team_local: "Irán", team_visitor: "Nueva Zelanda", date: "2026-06-15" },
  { match_number: 39, group_name: "G", team_local: "Bélgica", team_visitor: "Irán", date: "2026-06-21" },
  { match_number: 40, group_name: "G", team_local: "Egipto", team_visitor: "Nueva Zelanda", date: "2026-06-21" },
  { match_number: 41, group_name: "G", team_local: "Bélgica", team_visitor: "Nueva Zelanda", date: "2026-06-26" },
  { match_number: 42, group_name: "G", team_local: "Egipto", team_visitor: "Irán", date: "2026-06-26" },
  { match_number: 43, group_name: "H", team_local: "España", team_visitor: "Cabo Verde", date: "2026-06-15" },
  { match_number: 44, group_name: "H", team_local: "Arabia Saudita", team_visitor: "Uruguay", date: "2026-06-15" },
  { match_number: 45, group_name: "H", team_local: "España", team_visitor: "Arabia Saudita", date: "2026-06-21" },
  { match_number: 46, group_name: "H", team_local: "Cabo Verde", team_visitor: "Uruguay", date: "2026-06-21" },
  { match_number: 47, group_name: "H", team_local: "España", team_visitor: "Uruguay", date: "2026-06-26" },
  { match_number: 48, group_name: "H", team_local: "Cabo Verde", team_visitor: "Arabia Saudita", date: "2026-06-26" },
  { match_number: 49, group_name: "I", team_local: "Francia", team_visitor: "Senegal", date: "2026-06-16" },
  { match_number: 50, group_name: "I", team_local: "Irak", team_visitor: "Noruega", date: "2026-06-16" },
  { match_number: 51, group_name: "I", team_local: "Francia", team_visitor: "Irak", date: "2026-06-22" },
  { match_number: 52, group_name: "I", team_local: "Senegal", team_visitor: "Noruega", date: "2026-06-22" },
  { match_number: 53, group_name: "I", team_local: "Francia", team_visitor: "Noruega", date: "2026-06-26" },
  { match_number: 54, group_name: "I", team_local: "Senegal", team_visitor: "Irak", date: "2026-06-26" },
  { match_number: 55, group_name: "J", team_local: "Argentina", team_visitor: "Argelia", date: "2026-06-16" },
  { match_number: 56, group_name: "J", team_local: "Austria", team_visitor: "Jordania", date: "2026-06-16" },
  { match_number: 57, group_name: "J", team_local: "Argentina", team_visitor: "Austria", date: "2026-06-22" },
  { match_number: 58, group_name: "J", team_local: "Argelia", team_visitor: "Jordania", date: "2026-06-22" },
  { match_number: 59, group_name: "J", team_local: "Argentina", team_visitor: "Jordania", date: "2026-06-27" },
  { match_number: 60, group_name: "J", team_local: "Argelia", team_visitor: "Austria", date: "2026-06-27" },
  { match_number: 61, group_name: "K", team_local: "Portugal", team_visitor: "Uzbekistán", date: "2026-06-23" },
  { match_number: 62, group_name: "K", team_local: "R.D. del Congo", team_visitor: "Colombia", date: "2026-06-17" },
  { match_number: 63, group_name: "K", team_local: "Portugal", team_visitor: "R.D. del Congo", date: "2026-06-17" },
  { match_number: 64, group_name: "K", team_local: "Uzbekistán", team_visitor: "Colombia", date: "2026-06-17" },
  { match_number: 65, group_name: "K", team_local: "Portugal", team_visitor: "Colombia", date: "2026-06-27" },
  { match_number: 66, group_name: "K", team_local: "Uzbekistán", team_visitor: "R.D. del Congo", date: "2026-06-27" },
  { match_number: 67, group_name: "L", team_local: "Inglaterra", team_visitor: "Croacia", date: "2026-06-17" },
  { match_number: 68, group_name: "L", team_local: "Ghana", team_visitor: "Panamá", date: "2026-06-17" },
  { match_number: 69, group_name: "L", team_local: "Inglaterra", team_visitor: "Ghana", date: "2026-06-23" },
  { match_number: 70, group_name: "L", team_local: "Croacia", team_visitor: "Panamá", date: "2026-06-23" },
  { match_number: 71, group_name: "L", team_local: "Inglaterra", team_visitor: "Panamá", date: "2026-06-27" },
  { match_number: 72, group_name: "L", team_local: "Croacia", team_visitor: "Ghana", date: "2026-06-27" },
];

// Plantillas para fases eliminatorias
export const KNOCKOUT_TEMPLATES = {
  2: {
    name: "Dieciséisavos",
    matches_count: 16,
    description: "16 equipos clasificados",
  },
  3: {
    name: "Octavos",
    matches_count: 8,
    description: "8 equipos ganadores de dieciséisavos",
  },
  4: {
    name: "Cuartos",
    matches_count: 4,
    description: "4 equipos ganadores de octavos",
  },
  5: {
    name: "Semifinales",
    matches_count: 2,
    description: "2 equipos ganadores de cuartos",
  },
  6: {
    name: "Final",
    matches_count: 1,
    description: "Campeón del Mundial 2026",
  },
};

// Todos los equipos del Mundial 2026 (48 equipos de fase de grupos)
export const ALL_TEAMS = [
  { team: "México", flag: "🇲🇽" },
  { team: "Sudáfrica", flag: "🇿🇦" },
  { team: "Corea del Sur", flag: "🇰🇷" },
  { team: "Rep. Checa", flag: "🇨🇿" },
  { team: "Canadá", flag: "🇨🇦" },
  { team: "Bosnia y Herz.", flag: "🇧🇦" },
  { team: "Qatar", flag: "🇶🇦" },
  { team: "Suiza", flag: "🇨🇭" },
  { team: "Brasil", flag: "🇧🇷" },
  { team: "Marruecos", flag: "🇲🇦" },
  { team: "Haití", flag: "🇭🇹" },
  { team: "Escocia", flag: "SCO" },
  { team: "EE.UU.", flag: "🇺🇸" },
  { team: "Paraguay", flag: "🇵🇾" },
  { team: "Australia", flag: "🇦🇺" },
  { team: "Turquía", flag: "🇹🇷" },
  { team: "Alemania", flag: "🇩🇪" },
  { team: "Curazao", flag: "🇨🇼" },
  { team: "Costa de Marfil", flag: "🇨🇮" },
  { team: "Ecuador", flag: "🇪🇨" },
  { team: "Países Bajos", flag: "🇳🇱" },
  { team: "Japón", flag: "🇯🇵" },
  { team: "Suecia", flag: "🇸🇪" },
  { team: "Túnez", flag: "🇹🇳" },
  { team: "Bélgica", flag: "🇧🇪" },
  { team: "Egipto", flag: "🇪🇬" },
  { team: "Irán", flag: "🇮🇷" },
  { team: "Nueva Zelanda", flag: "🇳🇿" },
  { team: "España", flag: "🇪🇸" },
  { team: "Cabo Verde", flag: "🇨🇻" },
  { team: "Arabia Saudita", flag: "🇸🇦" },
  { team: "Uruguay", flag: "🇺🇾" },
  { team: "Francia", flag: "🇫🇷" },
  { team: "Senegal", flag: "🇸🇳" },
  { team: "Irak", flag: "🇮🇶" },
  { team: "Noruega", flag: "🇳🇴" },
  { team: "Argentina", flag: "🇦🇷" },
  { team: "Argelia", flag: "🇩🇿" },
  { team: "Austria", flag: "🇦🇹" },
  { team: "Jordania", flag: "🇯🇴" },
  { team: "Portugal", flag: "🇵🇹" },
  { team: "R.D. del Congo", flag: "🇨🇩" },
  { team: "Uzbekistán", flag: "🇺🇿" },
  { team: "Colombia", flag: "🇨🇴" },
  { team: "Inglaterra", flag: "ENG" },
  { team: "Croacia", flag: "🇭🇷" },
  { team: "Ghana", flag: "🇬🇭" },
  { team: "Panamá", flag: "🇵🇦" },
];
